import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import {BsArrowRight } from 'react-icons/bs'
import Link from 'next/link';

export default function Home() {

  


  return (
    <div className={styles.container}>
      <Head>
        <title>Formify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.logo}>formi.fy</p>
        <div className={styles.homepageContainer}>
          <p className={styles.subTitle}>Onchain. Decentralized. Low gas fees</p>
          <h1 className={styles.title}>Create <span className={styles.gradient}>Token Gated</span> Forms</h1>
          <Link href={'/create-form'}>
            <button className={styles.btn}>Create Form <BsArrowRight className={styles.arrow}/></button>
          </Link>
        </div>
      </main>
      <footer>
        <p className={styles.footer}>Created By @mitej23 in Mumbai</p>
      </footer>
    </div>
  )
}
